# Generated by Django 4.2 on 2023-06-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=123)),
            ],
        ),
    ]
