# Generated by Django 4.2 on 2023-06-05 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('pic', models.ImageField(upload_to='img')),
                ('quantity', models.IntegerField(default=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Add_to_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('pic', models.ImageField(upload_to='img')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.add_products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.user')),
            ],
        ),
    ]
